[package]
name = "rocketsim_test"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[example]]
name = "stress_v2"
required-features = ["v2"]

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.6.0", features = ["derive"] }
fastrand = "2.3.0"
glam.workspace = true
rocketsim = { path = "../rocketsim" }
rocketsim_rs = { version = "=0.37.0", default-features = false, optional = true }
zstd = "0.14"

[features]
v2 = ["dep:rocketsim_rs"]
