[workspace]
package.version = "0.2.0"
package.license-file = "LICENSE"
resolver = "3"
members = [
  "rocketsim",
  "rocketsim_derive",
  "rocketsim_test",
  "rocketsim_vis",
]

[workspace.dependencies]
glam = { version = "0.33.5", features = ["debug-glam-assert"] }
rustc-hash = "2.1.2"

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
debug = true
lto = true
panic = "abort"

# TODO: Temporary
[profile.test]
opt-level = 0
debug = true
