[workspace]
members = ["rocketsim", "rocketsim/rocketsim_derive"]
default-members = ["rocketsim"]
resolver = "3"
package.license-file = "LICENSE"
package.version = "0.2.0"

[profile.release]
debug = true
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 1

# TODO: Temporary
[profile.test]
opt-level = 0
debug = true