[package]
name = "rocketsim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Simulate Rocket League games at maximum efficiency"
documentation.workspace = true
readme = "../README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
arrayvec = "0.7.6"
byteorder = "1.5.0"
fastrand = "2.3.0"
fern = "0.7.1"
glam.workspace = true
log = "0.4.29"
rustc-hash.workspace = true

[target.'cfg(not(any(target_arch = "x86", target_arch = "x86_64")))'.dependencies]
# use glam with experimental support for portable SIMD when not running on x86
# architectures
glam = { workspace = true, features = ["core-simd"], optional = true }

[lints.clippy]
all = "warn"
# nursery = "warn"
# pedantic = "warn"
