[package]
name = "rocketsim"
edition = "2024"
license-file.workspace = true
version.workspace = true

[dependencies]
ahash = "0.8.12"
arrayvec = "0.7.6"
byteorder = "1.5.0"
fastrand = "2.3.0"
log = "0.4.29"
env_logger = "0.11.8"
glam = { workspace = true }
derive_hash_fast = "0.2.3"
zerocopy = { version = "0.8.34", features = ["derive"] }
rocketsim_derive = { path = "./rocketsim_derive" }

### OPTIONAL VISUALIZER DEPENDENCIES ###
miniquad = { version = "0.4.8", optional = true }
egui = { version = "0.33.3", optional = true }
egui-miniquad = { version = "0.16.0", optional = true }
raw-window-handle = { version = "0.6.2", optional = true }
png = { version = "0.18.0", optional = true }

[features]
# default = ["vis"]
vis = [
    "dep:miniquad",
    "dep:egui",
    "dep:egui-miniquad",
    "dep:raw-window-handle",
    "dep:png"
]

[dev-dependencies]
rocketsim_rs = "0.36.0" # For comparing to original C++ RocketSim in tests
device_query = "4.0.1" # For the RocketSimVis example
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
clap = { version = "4.6.0", features = ["derive"] }

[lints.clippy]
all = "warn"
# nursery = "warn"
# pedantic = "warn"

[[example]]
name = "rocket_sim_vis_compare"
required-features = ["vis"]

[[example]]
name = "vis"
required-features = ["vis"]
